/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JakobHenerey20231 (https://sketchfab.com/JakobHenerey20231)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yellow-metal-cube-58bcde745f6b48c9be24d6091f06f1d5
Title: Yellow Metal Cube
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/all";
gsap.registerPlugin(ScrollTrigger);

const Cube = (props) => {
  const cubeRef = useRef();
  const divRef = useRef();

  useGSAP(() => {
    gsap.to(cubeRef.current.position, {
      z: cubeRef.current.position.y - 50,
      scrollTrigger: {
        trigger: divRef.current,
        start: "35% 80%",
        end: "35% 60%",
        scrub: true,
        // markers: true,
      },
    });
    gsap.from(cubeRef.current.position, {
      // x: cubeRef.current.position.x + 50,
      z: cubeRef.current.position.z - 50,
      duration: 1.5,
    });
    gsap.to(cubeRef.current.position, {
      x: cubeRef.current.position.x + 2,
      //   z: cubeRef.current.position.z + 2,
      duration: 3,
      repeat: -1,
      yoyo: true,
    });
  });

  const { nodes, materials } = useGLTF("/models/cubeLight.glb");
  return (
    <>
      <Html>
        <div
          style={{ height: "10vh", position: "relative" }}
          ref={divRef}
        ></div>
      </Html>
      <group {...props} dispose={null} ref={cubeRef}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Material.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </>
  );
};

useGLTF.preload("/models/cubeLight.glb");

export default Cube;
