/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { useGSAP } from "@gsap/react";
import { Float, Html, useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useRef } from "react";
import { ScrollTrigger } from "gsap/all";
gsap.registerPlugin(ScrollTrigger);

const ReactLogo = (props) => {
  const { nodes, materials } = useGLTF("/models/react.glb");

  const reactRef = useRef();
  const divRef = useRef();

  useGSAP(() => {
    
    gsap.to(reactRef.current.position, {
      z: reactRef.current.position.z - 50,
      scrollTrigger: {
        trigger: divRef.current,
        start: "35% 80%",
        end: "35% 60%",
        scrub: true,
        // markers: true,
      },
    });

    gsap.from(reactRef.current.position, {
      // x: reactRef.current.position.x + 50,
      z: reactRef.current.position.z - 50,
      duration: 1.5,
    });
  });

  return (
    <>
      <Html>
        <div
          style={{ height: "10vh", position: "relative" }}
          ref={divRef}
        ></div>
      </Html>
      <Float floatIntensity={1}>
        <group
          position={[8, 8, 0]}
          scale={2.3}
          {...props}
          dispose={null}
          ref={reactRef}
        >
          <mesh
            geometry={nodes["React-Logo_Material002_0"].geometry}
            material={materials["Material.002"]}
            position={[0, 0.079, 0.181]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.392, 0.392, 0.527]}
          />
        </group>
      </Float>
    </>
  );
};

useGLTF.preload("models/react.glb");

export default ReactLogo;
