/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: azzajess (https://sketchfab.com/azzajess)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiked-ball-b03e6a597b794953977c7d60c27492bd
Title: Spiked Ball
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/all";
gsap.registerPlugin(ScrollTrigger);

const SpikeBall = (props) => {
  const ballRef = useRef();
  const divRef = useRef();

  useGSAP(() => {

    gsap.to(ballRef.current.position, {
      x: ballRef.current.position.x + 30,
      z: ballRef.current.position.z + 30,
      scrollTrigger: {
        trigger: divRef.current,
        start: "35% 80%",
        end: "35% 60%",
        scrub: true,
        // markers: true,
      },
    });

    gsap.from(ballRef.current.position, {
      x: ballRef.current.position.x + 50,
      z: ballRef.current.position.z + 50,
      duration: 1.5,
    });
    gsap.to(ballRef.current.position, {
      y: ballRef.current.position.y - 2,
      //   z: ballRef.current.position.z + 2,
      duration: 3,
      repeat: -1,
      yoyo: true,
    });
  });
  const { nodes, materials } = useGLTF("/models/spiked_ball.glb");
  return (
    <>
      <Html>
        <div
          style={{ height: "10vh", position: "relative" }}
          ref={divRef}
        ></div>
      </Html>
      <group {...props} dispose={null} ref={ballRef}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Projectile2HP_map1_0.geometry}
          material={materials.map1}
        />
      </group>
    </>
  );
};

useGLTF.preload("/models/spiked_ball.glb");

export default SpikeBall;

// rembrandt

// city
// Made by @NikkitaFTW & contributors inspired by the gltfjsx cli
