/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: prototypus (https://sketchfab.com/prototypus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rgs-vr-headset-prototype-6363621f57554bfd8b6fd8e049f83f34
Title: RGS_VR_headset_prototype
*/
"use client";

import React, { useRef } from "react";
import { useFrame, useLoader } from "@react-three/fiber";
import { Html, useGLTF } from "@react-three/drei";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/all";

gsap.registerPlugin(ScrollTrigger);

// import { ExtendedColors, Overwrite, NodeProps, NonFunctionKeys, Vector3, Euler, Matrix4, Quaternion, Layers } from "@react-three/fiber";
// import { EventHandlers } from "@react-three/fiber/dist/declarations/src/core/events";
// import { Group, Object3DEventMap } from "three";

const Vrman = (props) => {
  const vrman = useRef("");
  const triggerRef = useRef();

  useFrame(() => {
    if (vrman.current) {
      vrman.current.rotation.y += 0.01;
    }
  });

  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/models/rgs_vr_headset_prototype.glb"
  );

  useGSAP(() => {
    gsap.to(vrman.current.position, {
      y: vrman.current.position.y + 100,
      scrollTrigger: {
        trigger: triggerRef.current,
        start: "40% bottom",
        end: "bottom 0%",
        scrub: true,
        // markers: true,
      },
    });

    gsap.from(vrman.current.position, {
      y: vrman.current.position.y - 50,
      duration: 2,
    });
  });

  return (
    <>
      <Html>
        <div
          ref={triggerRef}
          style={{ height: "100vh", position: "relative" }}
        ></div>
      </Html>

      <group {...props} dispose={null} ref={vrman}>
        <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={150.06092}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.material}
              position={[-0.00005, 0.15261, 0.02681]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.material_0}
              position={[0.05371, 0.22436, -0.06776]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.material_0}
              position={[0.05372, 0.22445, -0.06778]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.material_0}
              position={[0.05117, 0.22425, -0.07112]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.material_0}
              position={[0.05117, 0.22439, -0.07118]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.material_0}
              position={[0.07188, 0.1806, -0.07333]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.material_0}
              position={[0.07172, 0.18061, -0.07327]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.material_0}
              position={[0.0716, 0.183, -0.07672]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.material_0}
              position={[0.04557, 0.19037, -0.09973]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.material_0}
              position={[0.04556, 0.19042, -0.0996]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.material_0}
              position={[0.05134, 0.19207, -0.09814]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.material_0}
              position={[0.05131, 0.19214, -0.09794]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials["17_-_Default"]}
              position={[-0.0717, 0.21507, -0.00205]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials.material_3}
              position={[0, 0.18972, -0.10567]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.material_4}
              position={[0.00257, 0.20915, 0.05911]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.material_5}
              position={[0, 0.19384, -0.06676]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_36.geometry}
              material={materials.material_6}
              position={[-0.00004, 0.19416, -0.05328]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.material_0}
              position={[0.05371, 0.22436, -0.06776]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.material_0}
              position={[0.05372, 0.22445, -0.06778]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_42.geometry}
              material={materials.material_7}
              position={[0.05374, 0.22444, -0.06779]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.material_0}
              position={[0.05117, 0.22425, -0.07112]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials.material_0}
              position={[0.05117, 0.22439, -0.07118]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials.material_0}
              position={[0.07188, 0.1806, -0.07333]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials["Material.001"]}
              position={[0.07191, 0.18056, -0.07333]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.material_0}
              position={[0.07172, 0.18061, -0.07327]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials.material_0}
              position={[0.0716, 0.183, -0.07672]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.material_0}
              position={[0.04557, 0.19037, -0.09973]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials.material_0}
              position={[0.04556, 0.19042, -0.0996]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_60.geometry}
              material={materials.material_0}
              position={[0.05134, 0.19207, -0.09814]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.material_0}
              position={[0.05131, 0.19214, -0.09794]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials.material_9}
              position={[0.05532, 0.20108, -0.08466]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials["17_-_Default"]}
              position={[-0.04558, 0.19041, -0.09967]}
              scale={[-0.001, 0.001, 0.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.material_5}
              position={[0, 0.19384, -0.06676]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_70.geometry}
              material={materials.material_5}
              position={[0, 0.19384, -0.06676]}
              scale={0.001}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_72.geometry}
              material={materials["17_-_Default"]}
              position={[0, 0.19233, -0.06694]}
              scale={[-0.001, 0.001, 0.001]}
            />
          </group>
        </group>
      </group>
    </>
  );
};

useGLTF.preload("/models/rgs_vr_headset_prototype.glb");
export default Vrman;
